import isPhone from "../../../lib/isPhone.ts";

/* generated by pull.js */
// lk: Enable by default on phones.
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "enabledByDefault": isPhone(),
  "name": "Auto-hiding block palette (LibreKitten version)",
  "description": "Hides the block palette unless you're hovering over it. Click the lock icon to lock it in place temporarily. Or use the \"category click\" mode to show/hide it when you click a block category. The \"category click or block creation\" mode is similar to \"category click\", but it also hides when you create a block.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    },
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    },
    {
      "name": "Forked by o97doge",
      "link": "https://scratch.mit.edu/users/o97doge/"
    }
  ],
  "info": [
    isPhone() ? {
      "text": "Some modes are not supported on phones.",
      "id": "phoneOtherModesNotSupported"
    } : {
      "text": "\"Palette area hover\" mode only extends the viewing area. If you want to be able to drag blocks into that area without them getting trashed, use one of the other modes.",
      "id": "hoverExplanation"
    },
  ],
  "dynamicDisable": true,
  "customCssVariables": [
    {
      "name": "lockDisplay",
      "value": {
        "type": "map",
        "source": {
          "type": "settingValue",
          "settingId": "toggle"
        },
        "options": {
          "hover": "flex",
          "cathover": "flex",
          "category": "none"
        }
      }
    },
    {
      "name": "placeholderDisplay",
      "value": {
        "type": "map",
        "source": {
          "type": "settingValue",
          "settingId": "toggle"
        },
        "options": {
          "hover": "block",
          "cathover": "none",
          "category": "none"
        }
      }
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Toggle on...",
      "id": "toggle",
      "type": "select",
      // lk: Don't show all options on phones
      "potentialValues": isPhone() ? [
        {
          "id": "category",
          "name": "Category click"
        },,
        {
          "id": "clickandcreate",
          "name": "LibreKitten: Category click or block creation"
        }
      ] : [
        {
          "id": "hover",
          "name": "Palette area hover"
        },
        {
          "id": "cathover",
          "name": "Category hover"
        },
        {
          "id": "category",
          "name": "Category click"
        },
        {
          "id": "clickandcreate",
          "name": "LibreKitten: Category click or block creation"
        }
      ],
      // lk: Set default option to click and create.
      "default": "clickandcreate"
    },
    {
      "dynamic": true,
      "name": "Animation speed",
      "id": "speed",
      "type": "select",
      "potentialValues": [
        {
          "id": "none",
          "name": "Instant"
        },
        {
          "id": "short",
          "name": "Quick"
        },
        {
          "id": "default",
          "name": "Default"
        },
        {
          "id": "long",
          "name": "Slow"
        }
      ],
      "default": "default"
    },
    {
      "name": "Open by default",
      "id": "lockLoad",
      "type": "boolean",
      "default": false
    }
  ],
  "tags": [
    "recommended"
  ]
};
export default manifest;
